
//list of people attending
export const ATTENDING_LIST_REQUEST = "ATTENDING_LIST_REQUEST";

export const ATTENDING_LIST_SUCCESS = "ATTENDING_LIST_SUCCESS";

export const ATTENDING_LIST_FAIL = "ATTENDING_LIST_FAIL";

//add to attending list

export const ATTENDING_ADD_REQUEST = "ATTENDING_ADD_REQUEST";

export const ATTENDING_ADD_SUCCESS = "ATTENDING_ADD_SUCCESS";

export const ATTENDING_ADD_FAIL = "ATTENDING_ADD_FAIL";

export const ATTENDING_ADD_RESET = "ATTENDING_ADD_RESET";



// removing from attending event

export const ATTENDING_REMOVE_REQUEST = "ATTENDING_REMOVE_REQUEST";

export const ATTENDING_REMOVE_SUCCESS = "ATTENDING_REMOVE_SUCCESS";

export const ATTENDING_REMOVE_FAIL = "ATTENDING_REMOVE_FAIL";

export const ATTENDING_REMOVE_RESET = "ATTENDING_REMOVE_RESET";
